services:
  pisces:
    container_name: pisces
    ports:
      - 61001:80
    volumes:
      - ~/Desktop/docker/universe/pisces/dist/:/usr/share/nginx/html/
      - ~/Desktop/docker/universe/pisces/default.conf:/etc/nginx/conf.d/default.conf
    image: nginx
